<?php
class ParserKodi {
  public static function parse($Kodi_data, $query_name, $debug_print) {
    $Kodi_data = json_decode($Kodi_data, true);
    return match ($query_name) {
      QueryKodi::$currently_playing => self::get_currently_playing($Kodi_data, $debug_print),
      QueryKodi::$properties => self::get_properties($Kodi_data, $debug_print),
      default => throw new Exception('Query name not found : ' . $query_name . ' in ParserKodi::parse() method'),
    };
  }

  public static function get_currently_playing($Kodi_data, $debug_print) {
    require_once 'autogenerated/get_currently_playing.php';
    $result = Result::fromJson($Kodi_data['result']);
    $parsed_data = new RootObject($result);
    if ($debug_print) {
      self::debug_print($parsed_data);
    }
    return $parsed_data;
  }

  public static function get_properties($Kodi_data, $debug_print) {
    require_once 'autogenerated/get_properties.php';
    $result = Result::fromJson($Kodi_data['result']);
    $parsed_data = new RootObject($result);
    if ($debug_print) {
      self::debug_print($parsed_data);
    }
    return $parsed_data;
  }

  public static function debug_print($result) {
    echo '<pre>';
    print_r($result);
    echo '</pre>';
  }
}
